app:
  title: Backstage My App
  baseUrl: http://localhost:3000

catalog:
  locations:
    - type: file
      target: file:///C:/Users/BDITUsers/backstage/component-template.yaml

jenkins:
  instances:
    - name: default
      baseUrl: https://jenkins.example.com
      username: backstage-bot

auth:
  environment: development
  providers:
    google:
      development:
        clientId: YOUR_GOOGLE_CLIENT_ID
        clientSecret: YOUR_GOOGLE_CLIENT_SECRET

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

proxy:
  endpoints:
    '/jenkins/api':
      target: http://localhost:8080

organization:
  name: My Company
